# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rticloud < Formula
  desc "Command-line interface for RTI Connext Cloud"
  homepage "https://github.com/realtimeinnovations/connext-cloud-cli"
  version "0.1.7"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.7/connext-cloud-cli_darwin_amd64.tar.gz"
      sha256 "f5ed6639b1a6c7ce5c5ed2a2e8a8b33f29d25106295903faa2df51ab704cd1c3"

      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.7/connext-cloud-cli_darwin_arm64.tar.gz"
      sha256 "4305d1693f6f0af27b8ad0c3dc91a6ce86fe75a3f951844d4f6a392097d78d5d"

      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.7/connext-cloud-cli_linux_amd64.tar.gz"
      sha256 "777b282b0e401f78517dccead3857409c55a9722ff4142ffb665c6f433ccb488"
      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.7/connext-cloud-cli_linux_arm64.tar.gz"
      sha256 "ad5f2dbda34cc6958e953060cc5db1182934266b76d5078293f363f05463fa83"
      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
  end

  test do
    system "#{bin}/rticloud", "--help"
  end
end
