# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rticloud < Formula
  desc "Command-line interface for RTI Connext Cloud"
  homepage "https://github.com/realtimeinnovations/connext-cloud-cli"
  version "0.1.5"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.5/connext-cloud-cli_darwin_amd64.tar.gz"
      sha256 "7c35b6683f861dff6c03a5924d9907580973a853995c94ed2a4228e0735121d0"

      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.5/connext-cloud-cli_darwin_arm64.tar.gz"
      sha256 "9e39ce88937712c5f2aba4cdb59ccb552e656cc78daa1948abf4fee631956416"

      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.5/connext-cloud-cli_linux_amd64.tar.gz"
      sha256 "15b52e0d4f168dd9b9eefd9b45f972bd0839f7af9d598f85668e9dbf3c0e21cd"
      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.5/connext-cloud-cli_linux_arm64.tar.gz"
      sha256 "8f4097f8bc3c1de0477aceb205b1873a288844d6e5201310bedb2982ce7d7af6"
      define_method(:install) do
        bin.install "rticloud"
        generate_completions_from_executable(bin/"rticloud", "completion")
      end
    end
  end

  test do
    system "#{bin}/rticloud", "--help"
  end
end
