# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rticloud < Formula
  desc "Command-line interface for RTI Connext Cloud"
  homepage "https://github.com/realtimeinnovations/connext-cloud-cli"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.0/connext-cloud-cli_darwin_amd64.tar.gz"
      sha256 "b33a61bd1326c74c2eb5eff65401d6e484f211fc1e3a5c481355e8540f705455"

      define_method(:install) do
        bin.install "rticloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.0/connext-cloud-cli_darwin_arm64.tar.gz"
      sha256 "15d9fd584e5d51663bd534c66c1b8ea64ef5e316a62eba27592916495c997629"

      define_method(:install) do
        bin.install "rticloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.0/connext-cloud-cli_linux_amd64.tar.gz"
      sha256 "8d8394dffee51242f664c69de633b4efcdbbb484099ecd5cd4b0b6c9bf922985"
      define_method(:install) do
        bin.install "rticloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/realtimeinnovations/connext-cloud-cli/releases/download/v0.1.0/connext-cloud-cli_linux_arm64.tar.gz"
      sha256 "9e002b348f1686a00040532b703704d36075e7ee1aba5daf3dd4934f08ef8db3"
      define_method(:install) do
        bin.install "rticloud"
      end
    end
  end

  test do
    system "#{bin}/rticloud", "--help"
  end
end
